### ISSUE TITLE
Consider splitting up system dependencies

### ISSUE THREAD

**Issue by mx** [digikar99/reader#3]
There's one system with two dependencies. In the interest of preventing library code from pulling in excess dependencies, I'd suggest:

* Create a new system for the tests, and move the 5am dependency there. For example, like so: https://lispcookbook.github.io/cl-cookbook/testing.html#asdf-integration
* Instead of unconditionally pulling in hash-set, instead default the operations to common-lisp sets (as gross as they are) and let the user define hash-set as the *set-function*.

**Comment by digikar99** [comment]
Thanks for pointing out! The default is now `cl:remove-duplicates`.

About the first point, I have ended up developing a preference for keeping the tests in the non-test source code files themselves. I had learnt this convention is at least followed in the rust ecosystem, so it is not totally out of the world. In this particular case, `fiveam` is a single dependency, not dependent on anything else, and in fairly wide usage, 

I think a separate file or system is preferable when the tests are much more than the actual non-test source code; otherwise, the tests in same file case seems alright.

**Comment by mx** [comment]
Well, fair enough. With the default changed, everything I brought up has been addressed. Cheers.
