### ISSUE TITLE
'equalp can be slow

### ISSUE THREAD

**Issue by bo-tato** [digikar99/reader#5]
Serapeum for example with it's `dict` hash table short hand uses `equal` for the test, what's the motivation for using `equalp`? I'm fairly new at lisp so I'm not saying should use one or the other, just curious.
But I did run into an issue with 'equalp hashtable and my program slowed to a crawl with just a few thousand elements in the hash table. I was storing `quri` as key, which is just a basic struct not even full CLOS class, but I guess recursing into each slot and doing case-insensitive string comparison for equalp is still slow on sbcl at least, even though it's just URI not even long strings.
I do:
```
(time
 (let ((ht (make-hash-table :test 'equal)))
   (loop for n upto 5000
         do (setf (gethash (quri:render-uri (quri:uri (format nil "https://somesite.com/path/?id=~a" n))) ht) t))))
```
it runs in 0.035 seconds, I change the test to 'equalp and change it to store quri rather than string:
```
(time
 (let ((ht (make-hash-table :test 'equalp)))
   (loop for n upto 5000
         do (setf (gethash (quri:uri (format nil "https://somesite.com/path/?id=~a" n)) ht) t))))
```
and it runs in 3 seconds.

**Comment by digikar99** [comment]
I went with `equalp` simply because it is the most general equality function - it works for arrays and structures too. (I just learnt that it does not work for other objects - [`equalp` boils down to `eq` for CLOS objects](http://www.lispworks.com/documentation/HyperSpec/Body/f_equalp.htm).)

But you can supply the equality function symbol as the first element of the hash-table reader macro. So, `{eq :a 2}` will create a hash-table with `eq` as the `:test` function.

Besides, you can also modify `*hash-table-function*` to use it with any other implementation of hash-tables (eg: [cl-custom-hash-table](https://github.com/metawilm/cl-custom-hash-table)).

**Comment by bo-tato** [comment]
Interesting thanks, so maybe it is slow because it is a structure and not a CLOS object, although eq comparison wouldn't be correct for me here. This is really wierd, I run it in sbcl profiler and it says it really is spending almost all it's time in equalp, in that hash table example, but then if I just use equalp:
```
(time
 (loop for n upto 10000
       do (equalp (quri:uri (format nil "https://somesite.com/path/?id=~a" n))
                  (quri:uri (format nil "https://somesite.com/path/?id=~a" (random 10000))))))
```
It runs perfectly fast, and I checked sxhash for each key is unique so it shouldn't be some worst case hash table doing a ton of comparisons. So I have no idea why it's actually slow but it's totally unrelated to reader now

**Comment by bo-tato** [comment]
If you're curious someone on reddit found the cause: https://www.reddit.com/r/Common_Lisp/comments/175qxu8/slow_hash_table_with_equalp/
It is cause for equalp hash tables, it uses `sb-int:psxhash` not `sxhash`, and sbcl defaults to using only the first four slots of the object when computing `psxhash`, and as I was inserting URI that were different paths on the same host, they were all the same in the first four slots, giving a bad hash table where every key has the same hash

**Comment by digikar99** [comment]
Very very interesting!
